// <auto-generated />
using System;
using EVDMS.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVDMS.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250929044903_DbContext.OnConfiguring")]
    partial class DbContextOnConfiguring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVDMS.Core.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DealerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UpdatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000064-0001-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            FullName = "System Admin",
                            HashedPassword = "admin_hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("00000064-0002-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            FullName = "EVM Staff Member",
                            HashedPassword = "evm_hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "evmstaff"
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0001-0000-0000-000000000000"),
                            FullName = "Manager 1",
                            HashedPassword = "hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "manager1"
                        },
                        new
                        {
                            Id = new Guid("00000002-0002-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0001-0000-0000-000000000000"),
                            FullName = "Staff 1",
                            HashedPassword = "hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "staff1"
                        },
                        new
                        {
                            Id = new Guid("00000002-0003-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0002-0000-0000-000000000000"),
                            FullName = "Manager 2",
                            HashedPassword = "hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "manager2"
                        },
                        new
                        {
                            Id = new Guid("00000002-0004-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0002-0000-0000-000000000000"),
                            FullName = "Staff 2",
                            HashedPassword = "hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "staff2"
                        },
                        new
                        {
                            Id = new Guid("00000002-0005-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0003-0000-0000-000000000000"),
                            FullName = "Manager 3",
                            HashedPassword = "hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "manager3"
                        },
                        new
                        {
                            Id = new Guid("00000002-0006-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0003-0000-0000-000000000000"),
                            FullName = "Staff 3",
                            HashedPassword = "hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "staff3"
                        },
                        new
                        {
                            Id = new Guid("00000002-0007-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0004-0000-0000-000000000000"),
                            FullName = "Manager 4",
                            HashedPassword = "hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "manager4"
                        },
                        new
                        {
                            Id = new Guid("00000002-0008-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0004-0000-0000-000000000000"),
                            FullName = "Staff 4",
                            HashedPassword = "hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "staff4"
                        },
                        new
                        {
                            Id = new Guid("00000002-0009-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0005-0000-0000-000000000000"),
                            FullName = "Manager 5",
                            HashedPassword = "hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "manager5"
                        },
                        new
                        {
                            Id = new Guid("00000002-000a-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0005-0000-0000-000000000000"),
                            FullName = "Staff 5",
                            HashedPassword = "hash",
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "staff5"
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000003-0001-0000-0000-000000000000"),
                            Address = "1 Main St",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "customer1@email.com",
                            FullName = "Customer 1",
                            IdCardNumber = "123456789011",
                            PhoneNumber = "987654321"
                        },
                        new
                        {
                            Id = new Guid("00000003-0002-0000-0000-000000000000"),
                            Address = "2 Main St",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "customer2@email.com",
                            FullName = "Customer 2",
                            IdCardNumber = "123456789012",
                            PhoneNumber = "987654322"
                        },
                        new
                        {
                            Id = new Guid("00000003-0003-0000-0000-000000000000"),
                            Address = "3 Main St",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "customer3@email.com",
                            FullName = "Customer 3",
                            IdCardNumber = "123456789013",
                            PhoneNumber = "987654323"
                        },
                        new
                        {
                            Id = new Guid("00000003-0004-0000-0000-000000000000"),
                            Address = "4 Main St",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "customer4@email.com",
                            FullName = "Customer 4",
                            IdCardNumber = "123456789014",
                            PhoneNumber = "987654324"
                        },
                        new
                        {
                            Id = new Guid("00000003-0005-0000-0000-000000000000"),
                            Address = "5 Main St",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "customer5@email.com",
                            FullName = "Customer 5",
                            IdCardNumber = "123456789015",
                            PhoneNumber = "987654325"
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Dealer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UpdatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Dealers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0001-0000-0000-000000000000"),
                            Address = "1 Street",
                            Code = "DLR001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "dealer1@email.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Auto-1",
                            PhoneNumber = "123456781",
                            Region = "North",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000001-0002-0000-0000-000000000000"),
                            Address = "2 Street",
                            Code = "DLR002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "dealer2@email.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Auto-2",
                            PhoneNumber = "123456782",
                            Region = "North",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000001-0003-0000-0000-000000000000"),
                            Address = "3 Street",
                            Code = "DLR003",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "dealer3@email.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Auto-3",
                            PhoneNumber = "123456783",
                            Region = "North",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000001-0004-0000-0000-000000000000"),
                            Address = "4 Street",
                            Code = "DLR004",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "dealer4@email.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Auto-4",
                            PhoneNumber = "123456784",
                            Region = "North",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000001-0005-0000-0000-000000000000"),
                            Address = "5 Street",
                            Code = "DLR005",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "dealer5@email.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Auto-5",
                            PhoneNumber = "123456785",
                            Region = "North",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripsion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VehicleModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSale")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UpdatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000006-0001-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0001-0000-0000-000000000000"),
                            Description = "New arrival",
                            IsSale = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            VehicleModelId = new Guid("00000005-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000006-0002-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0002-0000-0000-000000000000"),
                            Description = "New arrival",
                            IsSale = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            VehicleModelId = new Guid("00000005-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000006-0003-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0003-0000-0000-000000000000"),
                            Description = "New arrival",
                            IsSale = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            VehicleModelId = new Guid("00000005-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000006-0004-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0004-0000-0000-000000000000"),
                            Description = "New arrival",
                            IsSale = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            VehicleModelId = new Guid("00000005-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000006-0005-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            DealerId = new Guid("00000001-0005-0000-0000-000000000000"),
                            Description = "New arrival",
                            IsSale = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            VehicleModelId = new Guid("00000005-0005-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("PromotionId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000008-0001-0000-0000-000000000000"),
                            AccountId = new Guid("00000002-0001-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000002-0001-0000-0000-000000000000"),
                            CustomerId = new Guid("00000003-0001-0000-0000-000000000000"),
                            InventoryId = new Guid("00000006-0001-0000-0000-000000000000"),
                            PromotionId = new Guid("00000007-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000008-0002-0000-0000-000000000000"),
                            AccountId = new Guid("00000002-0003-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000002-0003-0000-0000-000000000000"),
                            CustomerId = new Guid("00000003-0002-0000-0000-000000000000"),
                            InventoryId = new Guid("00000006-0002-0000-0000-000000000000"),
                            PromotionId = new Guid("00000007-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000008-0003-0000-0000-000000000000"),
                            AccountId = new Guid("00000002-0005-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000002-0005-0000-0000-000000000000"),
                            CustomerId = new Guid("00000003-0003-0000-0000-000000000000"),
                            InventoryId = new Guid("00000006-0003-0000-0000-000000000000"),
                            PromotionId = new Guid("00000007-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000008-0004-0000-0000-000000000000"),
                            AccountId = new Guid("00000002-0007-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000002-0007-0000-0000-000000000000"),
                            CustomerId = new Guid("00000003-0004-0000-0000-000000000000"),
                            InventoryId = new Guid("00000006-0004-0000-0000-000000000000"),
                            PromotionId = new Guid("00000007-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000008-0005-0000-0000-000000000000"),
                            AccountId = new Guid("00000002-0009-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000002-0009-0000-0000-000000000000"),
                            CustomerId = new Guid("00000003-0005-0000-0000-000000000000"),
                            InventoryId = new Guid("00000006-0005-0000-0000-000000000000"),
                            PromotionId = new Guid("00000007-0005-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Payed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UpdatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000009-0001-0000-0000-000000000000"),
                            BasePrice = 35000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000002-0001-0000-0000-000000000000"),
                            DiscountPrice = 700m,
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinalPrice = 34300m,
                            IsSuccess = false,
                            OrderId = new Guid("00000008-0001-0000-0000-000000000000"),
                            Payed = 1000m,
                            PaymentMethod = "Card",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000002-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000009-0002-0000-0000-000000000000"),
                            BasePrice = 35000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000002-0003-0000-0000-000000000000"),
                            DiscountPrice = 1400m,
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinalPrice = 33600m,
                            IsSuccess = false,
                            OrderId = new Guid("00000008-0002-0000-0000-000000000000"),
                            Payed = 1000m,
                            PaymentMethod = "Card",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000002-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000009-0003-0000-0000-000000000000"),
                            BasePrice = 35000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000002-0005-0000-0000-000000000000"),
                            DiscountPrice = 2100m,
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinalPrice = 32900m,
                            IsSuccess = false,
                            OrderId = new Guid("00000008-0003-0000-0000-000000000000"),
                            Payed = 1000m,
                            PaymentMethod = "Card",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000002-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000009-0004-0000-0000-000000000000"),
                            BasePrice = 35000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000002-0007-0000-0000-000000000000"),
                            DiscountPrice = 2800m,
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinalPrice = 32200m,
                            IsSuccess = false,
                            OrderId = new Guid("00000008-0004-0000-0000-000000000000"),
                            Payed = 1000m,
                            PaymentMethod = "Card",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000002-0007-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000009-0005-0000-0000-000000000000"),
                            BasePrice = 35000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000002-0009-0000-0000-000000000000"),
                            DiscountPrice = 3500m,
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinalPrice = 31500m,
                            IsSuccess = false,
                            OrderId = new Guid("00000008-0005-0000-0000-000000000000"),
                            Payed = 1000m,
                            PaymentMethod = "Card",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000002-0009-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PercentDiscount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0001-0000-0000-000000000000"),
                            Code = "SALE1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sale 1",
                            PercentDiscount = 2
                        },
                        new
                        {
                            Id = new Guid("00000007-0002-0000-0000-000000000000"),
                            Code = "SALE2",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sale 2",
                            PercentDiscount = 4
                        },
                        new
                        {
                            Id = new Guid("00000007-0003-0000-0000-000000000000"),
                            Code = "SALE3",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sale 3",
                            PercentDiscount = 6
                        },
                        new
                        {
                            Id = new Guid("00000007-0004-0000-0000-000000000000"),
                            Code = "SALE4",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sale 4",
                            PercentDiscount = 8
                        },
                        new
                        {
                            Id = new Guid("00000007-0005-0000-0000-000000000000"),
                            Code = "SALE5",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sale 5",
                            PercentDiscount = 10
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UpdatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Staff member of a dealership.",
                            Name = "Dealer Staff",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Manager of a dealership.",
                            Name = "Dealer Manager",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Electric Vehicle Manufacturer staff.",
                            Name = "EVM Staff",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "System Administrator.",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.TestDrive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ScheduledDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("TestDrives");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0000000a-0001-0000-0000-000000000000"),
                            CustomerId = new Guid("00000003-0001-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            IsSuccess = false,
                            ScheduledDateTime = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleModelId = new Guid("00000005-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0000000a-0002-0000-0000-000000000000"),
                            CustomerId = new Guid("00000003-0002-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            IsSuccess = false,
                            ScheduledDateTime = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleModelId = new Guid("00000005-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0000000a-0003-0000-0000-000000000000"),
                            CustomerId = new Guid("00000003-0003-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            IsSuccess = false,
                            ScheduledDateTime = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleModelId = new Guid("00000005-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0000000a-0004-0000-0000-000000000000"),
                            CustomerId = new Guid("00000003-0004-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            IsSuccess = false,
                            ScheduledDateTime = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleModelId = new Guid("00000005-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0000000a-0005-0000-0000-000000000000"),
                            CustomerId = new Guid("00000003-0005-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            IsSuccess = false,
                            ScheduledDateTime = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleModelId = new Guid("00000005-0005-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.VehicleConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InteriorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UpdatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarrantyPeriod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VehicleConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000004-0001-0000-0000-000000000000"),
                            BasePrice = 35000m,
                            Color = "White",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            InteriorType = "Cloth",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            VersionName = "Standard",
                            WarrantyPeriod = 36
                        },
                        new
                        {
                            Id = new Guid("00000004-0002-0000-0000-000000000000"),
                            BasePrice = 35000m,
                            Color = "White",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            InteriorType = "Cloth",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            VersionName = "Standard",
                            WarrantyPeriod = 36
                        },
                        new
                        {
                            Id = new Guid("00000004-0003-0000-0000-000000000000"),
                            BasePrice = 35000m,
                            Color = "White",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            InteriorType = "Cloth",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            VersionName = "Standard",
                            WarrantyPeriod = 36
                        },
                        new
                        {
                            Id = new Guid("00000004-0004-0000-0000-000000000000"),
                            BasePrice = 35000m,
                            Color = "White",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            InteriorType = "Cloth",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            VersionName = "Standard",
                            WarrantyPeriod = 36
                        },
                        new
                        {
                            Id = new Guid("00000004-0005-0000-0000-000000000000"),
                            BasePrice = 35000m,
                            Color = "White",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            InteriorType = "Cloth",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtTick = 638396640000000000L,
                            UpdatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            VersionName = "Standard",
                            WarrantyPeriod = 36
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("FeatureIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleConfigId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000005-0001-0000-0000-000000000000"),
                            Brand = "Tesla",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Description",
                            ImgUrl = "Hahahaha",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Model 1",
                            ReleaseYear = 2022,
                            VehicleConfigId = new Guid("00000004-0001-0000-0000-000000000000"),
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("00000005-0002-0000-0000-000000000000"),
                            Brand = "Tesla",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Description",
                            ImgUrl = "Hahahaha",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Model 2",
                            ReleaseYear = 2022,
                            VehicleConfigId = new Guid("00000004-0002-0000-0000-000000000000"),
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("00000005-0003-0000-0000-000000000000"),
                            Brand = "Tesla",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Description",
                            ImgUrl = "Hahahaha",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Model 3",
                            ReleaseYear = 2022,
                            VehicleConfigId = new Guid("00000004-0003-0000-0000-000000000000"),
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("00000005-0004-0000-0000-000000000000"),
                            Brand = "Tesla",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Description",
                            ImgUrl = "Hahahaha",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Model 4",
                            ReleaseYear = 2022,
                            VehicleConfigId = new Guid("00000004-0004-0000-0000-000000000000"),
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("00000005-0005-0000-0000-000000000000"),
                            Brand = "Tesla",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = 638396640000000000L,
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Description",
                            ImgUrl = "Hahahaha",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Model 5",
                            ReleaseYear = 2022,
                            VehicleConfigId = new Guid("00000004-0005-0000-0000-000000000000"),
                            VehicleType = "Sedan"
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Account", b =>
                {
                    b.HasOne("EVDMS.Core.Entities.Dealer", "Dealer")
                        .WithMany("Accounts")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EVDMS.Core.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Feature", b =>
                {
                    b.HasOne("EVDMS.Core.Entities.VehicleModel", null)
                        .WithMany("Features")
                        .HasForeignKey("VehicleModelId");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Feedback", b =>
                {
                    b.HasOne("EVDMS.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Inventory", b =>
                {
                    b.HasOne("EVDMS.Core.Entities.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDMS.Core.Entities.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Order", b =>
                {
                    b.HasOne("EVDMS.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EVDMS.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDMS.Core.Entities.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EVDMS.Core.Entities.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Customer");

                    b.Navigation("Inventory");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Payment", b =>
                {
                    b.HasOne("EVDMS.Core.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("EVDMS.Core.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.TestDrive", b =>
                {
                    b.HasOne("EVDMS.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDMS.Core.Entities.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.VehicleModel", b =>
                {
                    b.HasOne("EVDMS.Core.Entities.VehicleConfig", "VehicleConfig")
                        .WithMany()
                        .HasForeignKey("VehicleConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleConfig");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Dealer", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Order", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("EVDMS.Core.Entities.VehicleModel", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
